In [346]:
#importing libs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import glob

In [347]:
#nifty 50 tickers 
ticks = [
     "ADANIENT.NS","ADANIPORTS.NS","APOLLOHOSP.NS", "ASIANPAINT.NS","AXISBANK.NS","BAJAJ-AUTO.NS",
    "BAJAJFINSV.NS","BAJFINANCE.NS","BEL.NS","BHARTIARTL.NS","CIPLA.NS","COALINDIA.NS","DRREDDY.NS",
    "EICHERMOT.NS","ETERNAL.NS","GRASIM.NS","HCLTECH.NS","HDFCBANK.NS","HDFCLIFE.NS","HINDALCO.NS",
    "HINDUNILVR.NS","ICICIBANK.NS","INDIGO.NS","INFY.NS","ITC.NS","JIOFIN.NS","JSWSTEEL.NS",
    "KOTAKBANK.NS","LT.NS","M&M.NS","MARUTI.NS","MAXHEALTH.NS","NESTLEIND.NS","NTPC.NS",
    "ONGC.NS","POWERGRID.NS","RELIANCE.NS","SBILIFE.NS","SBIN.NS","SHRIRAMFIN.NS","SUNPHARMA.NS",
    "TATACONSUM.NS","TATASTEEL.NS","TCS.NS","TECHM.NS","TITAN.NS","TMPV.NS","TRENT.NS",
    "ULTRACEMCO.NS","WIPRO.NS"]




print("Total companies:", len(ticks))

Total companies: 50

In [374]:
df = yf.download(
    ticks,
    start="2006-01-01",
    end="2026-08-31",
    progress=False,
    group_by="ticker",
    threads=True
)

In [375]:
df.head()

Ticker        SBIN.NS                                               \
Price            Open       High        Low      Close      Volume
Date
2006-01-02  65.606269  65.983728  64.862135  65.059853  21240601.0
2006-01-03  65.289921  65.786008  65.138934  65.573914  17462401.0
2006-01-04  65.836328  66.361181  65.836328  65.994507  19420938.0
2006-01-05  66.260513  67.975263  66.087957  67.676888  42574671.0
2006-01-06  67.655344  68.302424  66.947157  67.594231  23846595.0

Ticker     AXISBANK.NS                                              ...  \
Price             Open       High        Low      Close     Volume  ...
Date                                                                ...
2006-01-02   51.017543  51.279618  50.056594  50.371086   715590.0  ...
2006-01-03   50.703054  51.332035  50.406034  50.598221   419965.0  ...
2006-01-04   51.192260  52.196887  50.842826  51.803772  1448085.0  ...
2006-01-05   51.803783  53.376241  51.375727  53.061752  3013255.0  ...
2006-01-06   53.987740  55.123403  53.131624  54.835121  2035155.0  ...

Ticker         INFY.NS                                                  \
Price             Open        High         Low       Close      Volume
Date
2006-01-02  118.209023  118.209023  116.872440  117.122070   6648000.0
2006-01-03  117.540774  118.523557  117.110318  118.205132   7959936.0
2006-01-04  118.370246  120.489121  117.745191  120.107803  12552928.0
2006-01-05  120.449762  120.681695  119.555431  120.092026   7556560.0
2006-01-06  119.899390  120.685616  118.651257  120.025185  17007808.0

Ticker     ADANIPORTS.NS
Price               Open High Low Close Volume
Date
2006-01-02           NaN  NaN NaN   NaN    NaN
2006-01-03           NaN  NaN NaN   NaN    NaN
2006-01-04           NaN  NaN NaN   NaN    NaN
2006-01-05           NaN  NaN NaN   NaN    NaN
2006-01-06           NaN  NaN NaN   NaN    NaN

[5 rows x 250 columns]

In [376]:
print(df.shape)
print(df.columns)

(5100, 250)
MultiIndex([(      'SBIN.NS',   'Open'),
            (      'SBIN.NS',   'High'),
            (      'SBIN.NS',    'Low'),
            (      'SBIN.NS',  'Close'),
            (      'SBIN.NS', 'Volume'),
            (  'AXISBANK.NS',   'Open'),
            (  'AXISBANK.NS',   'High'),
            (  'AXISBANK.NS',    'Low'),
            (  'AXISBANK.NS',  'Close'),
            (  'AXISBANK.NS', 'Volume'),
            ...
            (      'INFY.NS',   'Open'),
            (      'INFY.NS',   'High'),
            (      'INFY.NS',    'Low'),
            (      'INFY.NS',  'Close'),
            (      'INFY.NS', 'Volume'),
            ('ADANIPORTS.NS',   'Open'),
            ('ADANIPORTS.NS',   'High'),
            ('ADANIPORTS.NS',    'Low'),
            ('ADANIPORTS.NS',  'Close'),
            ('ADANIPORTS.NS', 'Volume')],
           names=['Ticker', 'Price'], length=250)

In [438]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 5100 entries, 2006-01-02 to 2026-08-28
Columns: 250 entries, ('SBIN.NS', 'Open') to ('ADANIPORTS.NS', 'Volume')
dtypes: float64(249), int64(1)
memory usage: 9.9 MB

In [378]:
df.isnull().sum()

Ticker         Price
SBIN.NS        Open        1
               High        1
               Low         1
               Close       1
               Volume      1
                        ...
ADANIPORTS.NS  Open      473
               High      473
               Low       473
               Close     473
               Volume    473
Length: 250, dtype: int64

In [ ]:
#checking if the stocks we requested were downloaded
available = df.columns.get_level_values("Ticker").unique()
print("Requested:", len(ticks))
print("Downloaded:", len(available))
missing_tickers = [t for t in ticks if t not in available]
print("Missing tickers:")
print(missing_tickers)

Requested: 50
Downloaded: 50
Missing tickers:
[]

In [ ]:
#checks availibilty of very stock
#like from what date to what date do we have actually usefull data
for ticker in ticks:
    data = df.xs(ticker, level="Ticker", axis=1)
    valid = data.dropna(how="all")#removes rows were all data are missing
    if not valid.empty:
        print(
            ticker,
            "Start:", valid.index.min().date(),
            "End:", valid.index.max().date()
        )
    else:
        print(ticker, "NO DATA")

ADANIENT.NS Start: 2006-01-02 End: 2026-08-28
ADANIPORTS.NS Start: 2007-11-27 End: 2026-08-28
APOLLOHOSP.NS Start: 2006-01-02 End: 2026-08-28
ASIANPAINT.NS Start: 2006-01-02 End: 2026-08-28
AXISBANK.NS Start: 2006-01-02 End: 2026-08-28
BAJAJ-AUTO.NS Start: 2006-01-02 End: 2026-08-28
BAJAJFINSV.NS Start: 2006-01-02 End: 2026-08-28
BAJFINANCE.NS Start: 2006-01-02 End: 2026-08-28
BEL.NS Start: 2006-01-02 End: 2026-08-28
BHARTIARTL.NS Start: 2006-01-02 End: 2026-08-28
CIPLA.NS Start: 2006-01-02 End: 2026-08-28
COALINDIA.NS Start: 2010-11-04 End: 2026-08-28
DRREDDY.NS Start: 2006-01-02 End: 2026-08-28
EICHERMOT.NS Start: 2006-01-02 End: 2026-08-28
ETERNAL.NS Start: 2021-07-23 End: 2026-08-28
GRASIM.NS Start: 2006-01-02 End: 2026-08-28
HCLTECH.NS Start: 2006-01-02 End: 2026-08-28
HDFCBANK.NS Start: 2006-01-02 End: 2026-08-28
HDFCLIFE.NS Start: 2017-11-17 End: 2026-08-28
HINDALCO.NS Start: 2006-01-02 End: 2026-08-28
HINDUNILVR.NS Start: 2006-01-02 End: 2026-08-28
ICICIBANK.NS Start: 2006-01-02 End: 2026-08-28
INDIGO.NS Start: 2015-11-10 End: 2026-08-28
INFY.NS Start: 2006-01-02 End: 2026-08-28
ITC.NS Start: 2006-01-02 End: 2026-08-28
JIOFIN.NS Start: 2023-08-21 End: 2026-08-28
JSWSTEEL.NS Start: 2006-01-02 End: 2026-08-28
KOTAKBANK.NS Start: 2006-01-02 End: 2026-08-28
LT.NS Start: 2006-01-02 End: 2026-08-28
M&M.NS Start: 2006-01-02 End: 2026-08-28
MARUTI.NS Start: 2006-01-02 End: 2026-08-28
MAXHEALTH.NS Start: 2020-08-21 End: 2026-08-28
NESTLEIND.NS Start: 2006-01-02 End: 2026-08-28
NTPC.NS Start: 2006-01-02 End: 2026-08-28
ONGC.NS Start: 2006-01-02 End: 2026-08-28
POWERGRID.NS Start: 2007-10-05 End: 2026-08-28
RELIANCE.NS Start: 2006-01-02 End: 2026-08-28
SBILIFE.NS Start: 2017-10-03 End: 2026-08-28
SBIN.NS Start: 2006-01-02 End: 2026-08-28
SHRIRAMFIN.NS Start: 2006-01-02 End: 2026-08-28
SUNPHARMA.NS Start: 2006-01-02 End: 2026-08-28
TATACONSUM.NS Start: 2006-01-02 End: 2026-08-28
TATASTEEL.NS Start: 2006-01-02 End: 2026-08-28
TCS.NS Start: 2006-01-02 End: 2026-08-28
TECHM.NS Start: 2006-08-28 End: 2026-08-28
TITAN.NS Start: 2006-01-02 End: 2026-08-28
TMPV.NS Start: 2006-01-02 End: 2026-08-28
TRENT.NS Start: 2006-01-02 End: 2026-08-28
ULTRACEMCO.NS Start: 2006-01-02 End: 2026-08-28
WIPRO.NS Start: 2006-01-02 End: 2026-08-28

In [ ]:
for ticker in ticks:
    data = df.xs(ticker, level="Ticker", axis=1)
    missing_dates = data.isna().all(axis=1)#checks is ever data on that date is null
    if missing_dates.any():
        print(ticker, "missing dates:", missing_dates.sum())

ADANIENT.NS missing dates: 1
ADANIPORTS.NS missing dates: 473
APOLLOHOSP.NS missing dates: 1
ASIANPAINT.NS missing dates: 1
AXISBANK.NS missing dates: 1
BAJAJ-AUTO.NS missing dates: 1
BAJAJFINSV.NS missing dates: 1
BAJFINANCE.NS missing dates: 1
BEL.NS missing dates: 1
BHARTIARTL.NS missing dates: 1
CIPLA.NS missing dates: 1
COALINDIA.NS missing dates: 1196
DRREDDY.NS missing dates: 1
EICHERMOT.NS missing dates: 1
ETERNAL.NS missing dates: 3835
GRASIM.NS missing dates: 1
HDFCBANK.NS missing dates: 1
HDFCLIFE.NS missing dates: 2928
HINDALCO.NS missing dates: 1
HINDUNILVR.NS missing dates: 1
ICICIBANK.NS missing dates: 1
INDIGO.NS missing dates: 2431
INFY.NS missing dates: 1
ITC.NS missing dates: 1
JIOFIN.NS missing dates: 4350
JSWSTEEL.NS missing dates: 1
KOTAKBANK.NS missing dates: 1
LT.NS missing dates: 1
M&M.NS missing dates: 1
MARUTI.NS missing dates: 1
MAXHEALTH.NS missing dates: 3606
NESTLEIND.NS missing dates: 1
NTPC.NS missing dates: 1
ONGC.NS missing dates: 1
POWERGRID.NS missing dates: 437
RELIANCE.NS missing dates: 1
SBILIFE.NS missing dates: 2896
SBIN.NS missing dates: 1
SHRIRAMFIN.NS missing dates: 1
SUNPHARMA.NS missing dates: 1
TATACONSUM.NS missing dates: 1
TATASTEEL.NS missing dates: 1
TCS.NS missing dates: 1
TECHM.NS missing dates: 162
TITAN.NS missing dates: 1
TMPV.NS missing dates: 1
TRENT.NS missing dates: 1
ULTRACEMCO.NS missing dates: 1
WIPRO.NS missing dates: 1

In [ ]:
#inside the actual training data 
for ticker in ticks:
    data = df.xs(ticker, level="Ticker", axis=1)
    valid = data.dropna(how="all")
    if not valid.empty:
        start = valid.index.min()
        end = valid.index.max()
        internal_missing = data.loc[start:end].isna().all(axis=1).sum()
        if internal_missing > 0:
            print(ticker, "internal missing:", internal_missing)

ADANIENT.NS internal missing: 1
ADANIPORTS.NS internal missing: 1
APOLLOHOSP.NS internal missing: 1
ASIANPAINT.NS internal missing: 1
AXISBANK.NS internal missing: 1
BAJAJ-AUTO.NS internal missing: 1
BAJAJFINSV.NS internal missing: 1
BAJFINANCE.NS internal missing: 1
BEL.NS internal missing: 1
BHARTIARTL.NS internal missing: 1
CIPLA.NS internal missing: 1
DRREDDY.NS internal missing: 1
EICHERMOT.NS internal missing: 1
GRASIM.NS internal missing: 1
HDFCBANK.NS internal missing: 1
HINDALCO.NS internal missing: 1
HINDUNILVR.NS internal missing: 1
ICICIBANK.NS internal missing: 1
INDIGO.NS internal missing: 1
INFY.NS internal missing: 1
ITC.NS internal missing: 1
JSWSTEEL.NS internal missing: 1
KOTAKBANK.NS internal missing: 1
LT.NS internal missing: 1
M&M.NS internal missing: 1
MARUTI.NS internal missing: 1
NESTLEIND.NS internal missing: 1
NTPC.NS internal missing: 1
ONGC.NS internal missing: 1
POWERGRID.NS internal missing: 1
RELIANCE.NS internal missing: 1
SBIN.NS internal missing: 1
SHRIRAMFIN.NS internal missing: 1
SUNPHARMA.NS internal missing: 1
TATACONSUM.NS internal missing: 1
TATASTEEL.NS internal missing: 1
TCS.NS internal missing: 1
TECHM.NS internal missing: 1
TITAN.NS internal missing: 1
TMPV.NS internal missing: 1
TRENT.NS internal missing: 1
ULTRACEMCO.NS internal missing: 1
WIPRO.NS internal missing: 1

In [ ]:
#gives date of where even one data is missing
for ticker in ticks:
    data = df.xs(ticker, level="Ticker", axis=1)
    valid = data.dropna(how="all")
    if not valid.empty:
        start = valid.index.min()
        end = valid.index.max()
        missing_dates = data.loc[start:end].isna().all(axis=1)
        if missing_dates.any():
            print(ticker)
            print(data.loc[start:end].index[missing_dates])

ADANIENT.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
ADANIPORTS.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
APOLLOHOSP.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
ASIANPAINT.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
AXISBANK.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
BAJAJ-AUTO.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
BAJAJFINSV.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
BAJFINANCE.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
BEL.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
BHARTIARTL.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
CIPLA.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
DRREDDY.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
EICHERMOT.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
GRASIM.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
HDFCBANK.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
HINDALCO.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
HINDUNILVR.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
ICICIBANK.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
INDIGO.NS
DatetimeIndex(['2026-05-01'], dtype='datetime64[s]', name='Date', freq=None)
INFY.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
ITC.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
JSWSTEEL.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
KOTAKBANK.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
LT.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
M&M.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
MARUTI.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
NESTLEIND.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
NTPC.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
ONGC.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
POWERGRID.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
RELIANCE.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
SBIN.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
SHRIRAMFIN.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
SUNPHARMA.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
TATACONSUM.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
TATASTEEL.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
TCS.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
TECHM.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
TITAN.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
TMPV.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
TRENT.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
ULTRACEMCO.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)
WIPRO.NS
DatetimeIndex(['2010-02-06'], dtype='datetime64[s]', name='Date', freq=None)

In [ ]:
for ticker in ticks:
    data = df.xs(ticker, level="Ticker", axis=1)
    valid = data.dropna(how="all")
    if not valid.empty:
        start = valid.index.min()
        end = valid.index.max()
        ticker_cols = df.columns[#gets all cloumns beloning to that stock
            df.columns.get_level_values("Ticker") == ticker
        ]
        subset = df.loc[start:end, ticker_cols]
        df.loc[start:end, ticker_cols] = subset.ffill()

In [ ]:
#verification
for ticker in ticks:
    data = df.xs(ticker, level="Ticker", axis=1)
    valid = data.dropna(how="all")
    if not valid.empty:
        start = valid.index.min()
        end = valid.index.max()
        internal_missing = data.loc[start:end].isna().all(axis=1).sum()
        if internal_missing > 0:
            print(ticker, "internal missing:", internal_missing)

In [ ]:
prices = df.xs("Close", level="Price", axis=1)
print(prices.head())

Ticker       GRASIM.NS  AXISBANK.NS  EICHERMOT.NS    SBIN.NS    ONGC.NS  \
Date
2006-01-02  174.747375    50.371086     17.029488  65.059853  56.022694
2006-01-03  181.576935    50.598221     17.059803  65.573914  56.923008
2006-01-04  182.879272    51.803772     16.984005  65.994507  55.750038
2006-01-05  187.822021    53.061752     16.972631  67.676888  55.477360
2006-01-06  186.741989    54.835121     16.991581  67.594231  56.561020

Ticker       TRENT.NS  TECHM.NS  TATASTEEL.NS  HINDUNILVR.NS     ITC.NS  ...  \
Date                                                                     ...
2006-01-02  66.942238       NaN     18.551781     127.266518  24.700657  ...
2006-01-03  67.672287       NaN     18.904217     128.016647  25.229574  ...
2006-01-04  68.388268       NaN     18.808765     127.233894  25.908354  ...
2006-01-05  68.602425       NaN     18.620310     127.070824  25.635090  ...
2006-01-06  68.724358       NaN     18.806316     126.222832  25.643900  ...

Ticker      SHRIRAMFIN.NS  APOLLOHOSP.NS       LT.NS  HDFCLIFE.NS      M&M.NS  \
Date
2006-01-02      16.759243     223.053406  156.289200          NaN   98.136497
2006-01-03      17.315449     222.876038  156.841309          NaN  100.158020
2006-01-04      18.069248     224.738144  158.502151          NaN  101.405777
2006-01-05      17.615507     231.322021  158.330948          NaN   99.790482
2006-01-06      17.439861     238.349243  157.586182          NaN   99.055382

Ticker      BHARTIARTL.NS  JIOFIN.NS   WIPRO.NS  ADANIPORTS.NS     INFY.NS
Date
2006-01-02     139.106674        NaN  40.266342            NaN  117.122070
2006-01-03     141.724762        NaN  41.251846            NaN  118.205132
2006-01-04     141.111130        NaN  41.958267            NaN  120.107803
2006-01-05     140.088440        NaN  41.343414            NaN  120.092026
2006-01-06     142.052002        NaN  41.225685            NaN  120.025185

[5 rows x 50 columns]

In [ ]:
prices = prices.loc["2015-01-01":]
print(prices.head())
print(prices.shape)

Ticker       GRASIM.NS  AXISBANK.NS  EICHERMOT.NS     SBIN.NS     ONGC.NS  \
Date
2015-01-01  490.923706   486.587585   1395.726074  274.925018  129.360733
2015-01-02  504.370941   497.469452   1379.228760  276.019440  131.297165
2015-01-05  506.268372   500.613068   1385.502441  273.830566  132.782318
2015-01-06  486.963226   482.718536   1349.411865  262.579620  125.262421
2015-01-07  493.088074   482.331573   1368.067505  262.798523  127.104820

Ticker        TRENT.NS    TECHM.NS  TATASTEEL.NS  HINDUNILVR.NS      ITC.NS  \
Date
2015-01-01  144.977051  450.911285     28.314106     626.796387  156.947998
2015-01-02  143.701202  453.118561     28.755144     624.730408  157.439621
2015-01-05  143.867401  445.558441     29.171680     628.325256  158.059494
2015-01-06  141.848557  440.779266     27.757555     640.225647  153.998474
2015-01-07  145.529449  438.719696     27.225508     662.704163  151.134369

Ticker      ...  SHRIRAMFIN.NS  APOLLOHOSP.NS       LT.NS  HDFCLIFE.NS  \
Date        ...
2015-01-01  ...     184.305008    1081.482666  840.127563          NaN
2015-01-02  ...     184.932007    1083.355835  857.847412          NaN
2015-01-05  ...     179.163834    1086.958008  869.781677          NaN
2015-01-06  ...     174.791748    1054.587769  840.770447          NaN
2015-01-07  ...     173.880554    1062.848145  838.758118          NaN

Ticker          M&M.NS  BHARTIARTL.NS  JIOFIN.NS   WIPRO.NS  ADANIPORTS.NS  \
Date
2015-01-01  553.622375     304.244568        NaN  90.125504     300.506409
2015-01-02  548.072876     306.047058        NaN  90.924942     300.318359
2015-01-05  545.298096     299.256256        NaN  91.088097     304.503082
2015-01-06  542.254944     296.908875        NaN  88.958961     302.669281
2015-01-07  547.849060     297.621429        NaN  88.281868     301.964081

Ticker         INFY.NS
Date
2015-01-01  359.981049
2015-01-02  367.055206
2015-01-05  363.900970
2015-01-06  356.298096
2015-01-07  358.002869

[5 rows x 50 columns]
(2882, 50)

In [ ]:
returns = prices.pct_change() #calculate %change
print(returns.head())

Ticker      GRASIM.NS  AXISBANK.NS  EICHERMOT.NS   SBIN.NS   ONGC.NS  \
Date
2015-01-01        NaN          NaN           NaN       NaN       NaN
2015-01-02   0.027392     0.022364     -0.011820  0.003981  0.014969
2015-01-05   0.003762     0.006319      0.004549 -0.007930  0.011311
2015-01-06  -0.038132    -0.035745     -0.026049 -0.041087 -0.056633
2015-01-07   0.012578    -0.000802      0.013825  0.000834  0.014708

Ticker      TRENT.NS  TECHM.NS  TATASTEEL.NS  HINDUNILVR.NS    ITC.NS  ...  \
Date                                                                   ...
2015-01-01       NaN       NaN           NaN            NaN       NaN  ...
2015-01-02 -0.008800  0.004895      0.015577      -0.003296  0.003132  ...
2015-01-05  0.001157 -0.016685      0.014486       0.005754  0.003937  ...
2015-01-06 -0.014033 -0.010726     -0.048476       0.018940 -0.025693  ...
2015-01-07  0.025949 -0.004673     -0.019168       0.035110 -0.018598  ...

Ticker      SHRIRAMFIN.NS  APOLLOHOSP.NS     LT.NS  HDFCLIFE.NS    M&M.NS  \
Date
2015-01-01            NaN            NaN       NaN          NaN       NaN
2015-01-02       0.003402       0.001732  0.021092          NaN -0.010024
2015-01-05      -0.031191       0.003325  0.013912          NaN -0.005063
2015-01-06      -0.024403      -0.029781 -0.033355          NaN -0.005581
2015-01-07      -0.005213       0.007833 -0.002393          NaN  0.010316

Ticker      BHARTIARTL.NS  JIOFIN.NS  WIPRO.NS  ADANIPORTS.NS   INFY.NS
Date
2015-01-01            NaN        NaN       NaN            NaN       NaN
2015-01-02       0.005924        NaN  0.008870      -0.000626  0.019651
2015-01-05      -0.022189        NaN  0.001794       0.013934 -0.008593
2015-01-06      -0.007844        NaN -0.023374      -0.006022 -0.020893
2015-01-07       0.002400        NaN -0.007611      -0.002330  0.004785

[5 rows x 50 columns]

In [360]:
print(returns.isna().sum())

Ticker
GRASIM.NS           1
AXISBANK.NS         1
EICHERMOT.NS        1
SBIN.NS             1
ONGC.NS             1
TRENT.NS            1
TECHM.NS            1
TATASTEEL.NS        1
HINDUNILVR.NS       1
ITC.NS              1
TITAN.NS            1
BAJAJFINSV.NS       1
TATACONSUM.NS       1
ICICIBANK.NS        1
HINDALCO.NS         1
KOTAKBANK.NS        1
MARUTI.NS           1
POWERGRID.NS        1
BEL.NS              1
TCS.NS              1
BAJFINANCE.NS       1
ETERNAL.NS       1618
ULTRACEMCO.NS       1
ASIANPAINT.NS       1
TMPV.NS             1
MAXHEALTH.NS     1389
HDFCBANK.NS         1
HCLTECH.NS          1
COALINDIA.NS        1
SBILIFE.NS        679
CIPLA.NS            1
DRREDDY.NS          1
BAJAJ-AUTO.NS       1
ADANIENT.NS         1
RELIANCE.NS         1
INDIGO.NS         213
JSWSTEEL.NS         1
SUNPHARMA.NS        1
NESTLEIND.NS        1
NTPC.NS             1
SHRIRAMFIN.NS       1
APOLLOHOSP.NS       1
LT.NS               1
HDFCLIFE.NS       711
M&M.NS              1
BHARTIARTL.NS       1
JIOFIN.NS        2133
WIPRO.NS            1
ADANIPORTS.NS       1
INFY.NS             1
dtype: int64

In [ ]:
missing_from_prices = [t for t in ticks if t not in prices.columns]
print("Missing from prices:")
print(missing_from_prices)

Missing from prices:
[]

In [ ]:
prices = prices.loc["2015-01-01":]
print(prices.head())
print("Shape:", prices.shape)

Ticker       GRASIM.NS  AXISBANK.NS  EICHERMOT.NS     SBIN.NS     ONGC.NS  \
Date
2015-01-01  490.923706   486.587585   1395.726074  274.925018  129.360733
2015-01-02  504.370941   497.469452   1379.228760  276.019440  131.297165
2015-01-05  506.268372   500.613068   1385.502441  273.830566  132.782318
2015-01-06  486.963226   482.718536   1349.411865  262.579620  125.262421
2015-01-07  493.088074   482.331573   1368.067505  262.798523  127.104820

Ticker        TRENT.NS    TECHM.NS  TATASTEEL.NS  HINDUNILVR.NS      ITC.NS  \
Date
2015-01-01  144.977051  450.911285     28.314106     626.796387  156.947998
2015-01-02  143.701202  453.118561     28.755144     624.730408  157.439621
2015-01-05  143.867401  445.558441     29.171680     628.325256  158.059494
2015-01-06  141.848557  440.779266     27.757555     640.225647  153.998474
2015-01-07  145.529449  438.719696     27.225508     662.704163  151.134369

Ticker      ...  SHRIRAMFIN.NS  APOLLOHOSP.NS       LT.NS  HDFCLIFE.NS  \
Date        ...
2015-01-01  ...     184.305008    1081.482666  840.127563          NaN
2015-01-02  ...     184.932007    1083.355835  857.847412          NaN
2015-01-05  ...     179.163834    1086.958008  869.781677          NaN
2015-01-06  ...     174.791748    1054.587769  840.770447          NaN
2015-01-07  ...     173.880554    1062.848145  838.758118          NaN

Ticker          M&M.NS  BHARTIARTL.NS  JIOFIN.NS   WIPRO.NS  ADANIPORTS.NS  \
Date
2015-01-01  553.622375     304.244568        NaN  90.125504     300.506409
2015-01-02  548.072876     306.047058        NaN  90.924942     300.318359
2015-01-05  545.298096     299.256256        NaN  91.088097     304.503082
2015-01-06  542.254944     296.908875        NaN  88.958961     302.669281
2015-01-07  547.849060     297.621429        NaN  88.281868     301.964081

Ticker         INFY.NS
Date
2015-01-01  359.981049
2015-01-02  367.055206
2015-01-05  363.900970
2015-01-06  356.298096
2015-01-07  358.002869

[5 rows x 50 columns]
Shape: (2882, 50)

In [ ]:
returns = prices.pct_change()
print(returns.head())

Ticker      GRASIM.NS  AXISBANK.NS  EICHERMOT.NS   SBIN.NS   ONGC.NS  \
Date
2015-01-01        NaN          NaN           NaN       NaN       NaN
2015-01-02   0.027392     0.022364     -0.011820  0.003981  0.014969
2015-01-05   0.003762     0.006319      0.004549 -0.007930  0.011311
2015-01-06  -0.038132    -0.035745     -0.026049 -0.041087 -0.056633
2015-01-07   0.012578    -0.000802      0.013825  0.000834  0.014708

Ticker      TRENT.NS  TECHM.NS  TATASTEEL.NS  HINDUNILVR.NS    ITC.NS  ...  \
Date                                                                   ...
2015-01-01       NaN       NaN           NaN            NaN       NaN  ...
2015-01-02 -0.008800  0.004895      0.015577      -0.003296  0.003132  ...
2015-01-05  0.001157 -0.016685      0.014486       0.005754  0.003937  ...
2015-01-06 -0.014033 -0.010726     -0.048476       0.018940 -0.025693  ...
2015-01-07  0.025949 -0.004673     -0.019168       0.035110 -0.018598  ...

Ticker      SHRIRAMFIN.NS  APOLLOHOSP.NS     LT.NS  HDFCLIFE.NS    M&M.NS  \
Date
2015-01-01            NaN            NaN       NaN          NaN       NaN
2015-01-02       0.003402       0.001732  0.021092          NaN -0.010024
2015-01-05      -0.031191       0.003325  0.013912          NaN -0.005063
2015-01-06      -0.024403      -0.029781 -0.033355          NaN -0.005581
2015-01-07      -0.005213       0.007833 -0.002393          NaN  0.010316

Ticker      BHARTIARTL.NS  JIOFIN.NS  WIPRO.NS  ADANIPORTS.NS   INFY.NS
Date
2015-01-01            NaN        NaN       NaN            NaN       NaN
2015-01-02       0.005924        NaN  0.008870      -0.000626  0.019651
2015-01-05      -0.022189        NaN  0.001794       0.013934 -0.008593
2015-01-06      -0.007844        NaN -0.023374      -0.006022 -0.020893
2015-01-07       0.002400        NaN -0.007611      -0.002330  0.004785

[5 rows x 50 columns]

In [365]:
print(returns.isna().sum())

Ticker
GRASIM.NS           1
AXISBANK.NS         1
EICHERMOT.NS        1
SBIN.NS             1
ONGC.NS             1
TRENT.NS            1
TECHM.NS            1
TATASTEEL.NS        1
HINDUNILVR.NS       1
ITC.NS              1
TITAN.NS            1
BAJAJFINSV.NS       1
TATACONSUM.NS       1
ICICIBANK.NS        1
HINDALCO.NS         1
KOTAKBANK.NS        1
MARUTI.NS           1
POWERGRID.NS        1
BEL.NS              1
TCS.NS              1
BAJFINANCE.NS       1
ETERNAL.NS       1618
ULTRACEMCO.NS       1
ASIANPAINT.NS       1
TMPV.NS             1
MAXHEALTH.NS     1389
HDFCBANK.NS         1
HCLTECH.NS          1
COALINDIA.NS        1
SBILIFE.NS        679
CIPLA.NS            1
DRREDDY.NS          1
BAJAJ-AUTO.NS       1
ADANIENT.NS         1
RELIANCE.NS         1
INDIGO.NS         213
JSWSTEEL.NS         1
SUNPHARMA.NS        1
NESTLEIND.NS        1
NTPC.NS             1
SHRIRAMFIN.NS       1
APOLLOHOSP.NS       1
LT.NS               1
HDFCLIFE.NS       711
M&M.NS              1
BHARTIARTL.NS       1
JIOFIN.NS        2133
WIPRO.NS            1
ADANIPORTS.NS       1
INFY.NS             1
dtype: int64

In [ ]:
missing_counts = returns.isna().sum()
print(missing_counts[missing_counts > 1])

Ticker
ETERNAL.NS      1618
MAXHEALTH.NS    1389
SBILIFE.NS       679
INDIGO.NS        213
HDFCLIFE.NS      711
JIOFIN.NS       2133
dtype: int64

In [ ]:
returns_clean = returns.dropna(how="all")
print(returns_clean.isna().sum())

Ticker
GRASIM.NS           0
AXISBANK.NS         0
EICHERMOT.NS        0
SBIN.NS             0
ONGC.NS             0
TRENT.NS            0
TECHM.NS            0
TATASTEEL.NS        0
HINDUNILVR.NS       0
ITC.NS              0
TITAN.NS            0
BAJAJFINSV.NS       0
TATACONSUM.NS       0
ICICIBANK.NS        0
HINDALCO.NS         0
KOTAKBANK.NS        0
MARUTI.NS           0
POWERGRID.NS        0
BEL.NS              0
TCS.NS              0
BAJFINANCE.NS       0
ETERNAL.NS       1617
ULTRACEMCO.NS       0
ASIANPAINT.NS       0
TMPV.NS             0
MAXHEALTH.NS     1388
HDFCBANK.NS         0
HCLTECH.NS          0
COALINDIA.NS        0
SBILIFE.NS        678
CIPLA.NS            0
DRREDDY.NS          0
BAJAJ-AUTO.NS       0
ADANIENT.NS         0
RELIANCE.NS         0
INDIGO.NS         212
JSWSTEEL.NS         0
SUNPHARMA.NS        0
NESTLEIND.NS        0
NTPC.NS             0
SHRIRAMFIN.NS       0
APOLLOHOSP.NS       0
LT.NS               0
HDFCLIFE.NS       710
M&M.NS              0
BHARTIARTL.NS       0
JIOFIN.NS        2132
WIPRO.NS            0
ADANIPORTS.NS       0
INFY.NS             0
dtype: int64

In [ ]:
mean_returns = returns.mean()
print(mean_returns)

Ticker
GRASIM.NS        0.000819
AXISBANK.NS      0.000542
EICHERMOT.NS     0.000797
SBIN.NS          0.000671
ONGC.NS          0.000416
TRENT.NS         0.001313
TECHM.NS         0.000619
TATASTEEL.NS     0.000906
HINDUNILVR.NS    0.000503
ITC.NS           0.000301
TITAN.NS         0.001092
BAJAJFINSV.NS    0.001164
TATACONSUM.NS    0.000892
ICICIBANK.NS     0.000729
HINDALCO.NS      0.000968
KOTAKBANK.NS     0.000558
MARUTI.NS        0.000665
POWERGRID.NS     0.000720
BEL.NS           0.001235
TCS.NS           0.000418
BAJFINANCE.NS    0.001454
ETERNAL.NS       0.001192
ULTRACEMCO.NS    0.000672
ASIANPAINT.NS    0.000589
TMPV.NS          0.000220
MAXHEALTH.NS     0.001747
HDFCBANK.NS      0.000521
HCLTECH.NS       0.000672
COALINDIA.NS     0.000503
SBILIFE.NS       0.000563
CIPLA.NS         0.000443
DRREDDY.NS       0.000376
BAJAJ-AUTO.NS    0.000781
ADANIENT.NS      0.001862
RELIANCE.NS      0.000809
INDIGO.NS        0.000959
JSWSTEEL.NS      0.001136
SUNPHARMA.NS     0.000483
NESTLEIND.NS     0.000680
NTPC.NS          0.000627
SHRIRAMFIN.NS    0.000973
APOLLOHOSP.NS    0.000918
LT.NS            0.000687
HDFCLIFE.NS      0.000392
M&M.NS           0.000802
BHARTIARTL.NS    0.000797
JIOFIN.NS        0.000161
WIPRO.NS         0.000372
ADANIPORTS.NS    0.000874
INFY.NS          0.000545
dtype: float64

In [ ]:
volatility = returns.std()
print(volatility)

Ticker
GRASIM.NS        0.017799
AXISBANK.NS      0.020419
EICHERMOT.NS     0.019428
SBIN.NS          0.020417
ONGC.NS          0.020655
TRENT.NS         0.023184
TECHM.NS         0.018415
TATASTEEL.NS     0.022408
HINDUNILVR.NS    0.014080
ITC.NS           0.015316
TITAN.NS         0.018401
BAJAJFINSV.NS    0.020344
TATACONSUM.NS    0.018662
ICICIBANK.NS     0.018897
HINDALCO.NS      0.023935
KOTAKBANK.NS     0.016321
MARUTI.NS        0.017094
POWERGRID.NS     0.015586
BEL.NS           0.022502
TCS.NS           0.015004
BAJFINANCE.NS    0.022236
ETERNAL.NS       0.029557
ULTRACEMCO.NS    0.016690
ASIANPAINT.NS    0.015587
TMPV.NS          0.026543
MAXHEALTH.NS     0.023161
HDFCBANK.NS      0.014041
HCLTECH.NS       0.016948
COALINDIA.NS     0.018043
SBILIFE.NS       0.016714
CIPLA.NS         0.016322
DRREDDY.NS       0.016608
BAJAJ-AUTO.NS    0.016031
ADANIENT.NS      0.032549
RELIANCE.NS      0.016941
INDIGO.NS        0.023368
JSWSTEEL.NS      0.020664
SUNPHARMA.NS     0.017718
NESTLEIND.NS     0.014344
NTPC.NS          0.016291
SHRIRAMFIN.NS    0.026687
APOLLOHOSP.NS    0.019465
LT.NS            0.016830
HDFCLIFE.NS      0.018205
M&M.NS           0.018955
BHARTIARTL.NS    0.018172
JIOFIN.NS        0.020753
WIPRO.NS         0.016178
ADANIPORTS.NS    0.023158
INFY.NS          0.016887
dtype: float64

In [ ]:
covariance = returns.cov()
print(covariance)

Ticker         GRASIM.NS  AXISBANK.NS  EICHERMOT.NS   SBIN.NS   ONGC.NS  \
Ticker
GRASIM.NS       0.000317     0.000161      0.000130  0.000162  0.000107
AXISBANK.NS     0.000161     0.000417      0.000149  0.000231  0.000112
EICHERMOT.NS    0.000130     0.000149      0.000377  0.000134  0.000083
SBIN.NS         0.000162     0.000231      0.000134  0.000417  0.000145
ONGC.NS         0.000107     0.000112      0.000083  0.000145  0.000427
TRENT.NS        0.000120     0.000132      0.000120  0.000127  0.000090
TECHM.NS        0.000083     0.000088      0.000068  0.000079  0.000076
TATASTEEL.NS    0.000186     0.000179      0.000145  0.000206  0.000194
HINDUNILVR.NS   0.000066     0.000069      0.000066  0.000051  0.000034
ITC.NS          0.000077     0.000081      0.000069  0.000097  0.000075
TITAN.NS        0.000116     0.000118      0.000115  0.000106  0.000075
BAJAJFINSV.NS   0.000156     0.000191      0.000152  0.000170  0.000101
TATACONSUM.NS   0.000128     0.000122      0.000116  0.000123  0.000085
ICICIBANK.NS    0.000139     0.000253      0.000135  0.000249  0.000111
HINDALCO.NS     0.000187     0.000186      0.000145  0.000210  0.000204
KOTAKBANK.NS    0.000104     0.000146      0.000107  0.000120  0.000067
MARUTI.NS       0.000129     0.000148      0.000166  0.000132  0.000089
POWERGRID.NS    0.000082     0.000078      0.000063  0.000095  0.000102
BEL.NS          0.000143     0.000149      0.000128  0.000178  0.000171
TCS.NS          0.000060     0.000059      0.000047  0.000052  0.000055
BAJFINANCE.NS   0.000156     0.000200      0.000170  0.000185  0.000104
ETERNAL.NS      0.000118     0.000096      0.000111  0.000116  0.000061
ULTRACEMCO.NS   0.000182     0.000143      0.000127  0.000150  0.000090
ASIANPAINT.NS   0.000097     0.000092      0.000105  0.000078  0.000038
TMPV.NS         0.000182     0.000200      0.000185  0.000220  0.000174
MAXHEALTH.NS    0.000055     0.000053      0.000073  0.000045  0.000032
HDFCBANK.NS     0.000105     0.000137      0.000101  0.000121  0.000056
HCLTECH.NS      0.000061     0.000065      0.000058  0.000057  0.000071
COALINDIA.NS    0.000094     0.000100      0.000080  0.000124  0.000175
SBILIFE.NS      0.000105     0.000112      0.000094  0.000106  0.000076
CIPLA.NS        0.000076     0.000067      0.000049  0.000067  0.000059
DRREDDY.NS      0.000071     0.000055      0.000049  0.000056  0.000056
BAJAJ-AUTO.NS   0.000102     0.000104      0.000128  0.000093  0.000083
ADANIENT.NS     0.000206     0.000200      0.000171  0.000251  0.000180
RELIANCE.NS     0.000106     0.000123      0.000103  0.000126  0.000123
INDIGO.NS       0.000116     0.000125      0.000108  0.000135  0.000057
JSWSTEEL.NS     0.000178     0.000174      0.000141  0.000172  0.000148
SUNPHARMA.NS    0.000097     0.000073      0.000065  0.000076  0.000072
NESTLEIND.NS    0.000067     0.000057      0.000056  0.000043  0.000038
NTPC.NS         0.000098     0.000106      0.000081  0.000124  0.000145
SHRIRAMFIN.NS   0.000179     0.000245      0.000177  0.000216  0.000130
APOLLOHOSP.NS   0.000090     0.000091      0.000090  0.000082  0.000066
LT.NS           0.000140     0.000167      0.000127  0.000172  0.000116
HDFCLIFE.NS     0.000124     0.000129      0.000103  0.000116  0.000073
M&M.NS          0.000141     0.000147      0.000161  0.000149  0.000100
BHARTIARTL.NS   0.000115     0.000093      0.000088  0.000103  0.000081
JIOFIN.NS       0.000101     0.000116      0.000114  0.000122  0.000109
WIPRO.NS        0.000073     0.000071      0.000055  0.000066  0.000079
ADANIPORTS.NS   0.000162     0.000170      0.000137  0.000200  0.000144
INFY.NS         0.000064     0.000075      0.000053  0.000064  0.000058

Ticker         TRENT.NS  TECHM.NS  TATASTEEL.NS  HINDUNILVR.NS    ITC.NS  ...  \
Ticker                                                                    ...
GRASIM.NS      0.000120  0.000083      0.000186       0.000066  0.000077  ...
AXISBANK.NS    0.000132  0.000088      0.000179       0.000069  0.000081  ...
EICHERMOT.NS   0.000120  0.000068      0.000145       0.000066  0.000069  ...
SBIN.NS        0.000127  0.000079      0.000206       0.000051  0.000097  ...
ONGC.NS        0.000090  0.000076      0.000194       0.000034  0.000075  ...
TRENT.NS       0.000538  0.000077      0.000131       0.000059  0.000087  ...
TECHM.NS       0.000077  0.000339      0.000096       0.000050  0.000048  ...
TATASTEEL.NS   0.000131  0.000096      0.000502       0.000054  0.000094  ...
HINDUNILVR.NS  0.000059  0.000050      0.000054       0.000198  0.000056  ...
ITC.NS         0.000087  0.000048      0.000094       0.000056  0.000235  ...
TITAN.NS       0.000121  0.000066      0.000124       0.000068  0.000069  ...
BAJAJFINSV.NS  0.000147  0.000091      0.000179       0.000068  0.000086  ...
TATACONSUM.NS  0.000116  0.000091      0.000147       0.000087  0.000075  ...
ICICIBANK.NS   0.000121  0.000079      0.000180       0.000060  0.000083  ...
HINDALCO.NS    0.000144  0.000109      0.000370       0.000059  0.000093  ...
KOTAKBANK.NS   0.000096  0.000063      0.000108       0.000064  0.000068  ...
MARUTI.NS      0.000108  0.000068      0.000137       0.000075  0.000064  ...
POWERGRID.NS   0.000076  0.000042      0.000107       0.000028  0.000053  ...
BEL.NS         0.000126  0.000081      0.000184       0.000047  0.000084  ...
TCS.NS         0.000049  0.000142      0.000074       0.000048  0.000042  ...
BAJFINANCE.NS  0.000167  0.000093      0.000175       0.000079  0.000082  ...
ETERNAL.NS     0.000160  0.000098      0.000151       0.000045  0.000064  ...
ULTRACEMCO.NS  0.000113  0.000078      0.000163       0.000070  0.000068  ...
ASIANPAINT.NS  0.000096  0.000058      0.000086       0.000085  0.000054  ...
TMPV.NS        0.000159  0.000108      0.000272       0.000062  0.000109  ...
MAXHEALTH.NS   0.000092  0.000073      0.000064       0.000040  0.000039  ...
HDFCBANK.NS    0.000098  0.000059      0.000111       0.000052  0.000060  ...
HCLTECH.NS     0.000059  0.000165      0.000089       0.000051  0.000045  ...
COALINDIA.NS   0.000081  0.000061      0.000167       0.000027  0.000066  ...
SBILIFE.NS     0.000098  0.000072      0.000113       0.000062  0.000059  ...
CIPLA.NS       0.000050  0.000050      0.000089       0.000041  0.000045  ...
DRREDDY.NS     0.000053  0.000058      0.000078       0.000049  0.000035  ...
BAJAJ-AUTO.NS  0.000096  0.000052      0.000109       0.000059  0.000058  ...
ADANIENT.NS    0.000185  0.000118      0.000253       0.000075  0.000101  ...
RELIANCE.NS    0.000110  0.000081      0.000139       0.000062  0.000065  ...
INDIGO.NS      0.000120  0.000055      0.000118       0.000051  0.000068  ...
JSWSTEEL.NS    0.000128  0.000093      0.000334       0.000062  0.000090  ...
SUNPHARMA.NS   0.000066  0.000072      0.000110       0.000045  0.000050  ...
NESTLEIND.NS   0.000064  0.000049      0.000053       0.000088  0.000044  ...
NTPC.NS        0.000082  0.000057      0.000144       0.000032  0.000059  ...
SHRIRAMFIN.NS  0.000164  0.000089      0.000200       0.000062  0.000085  ...
APOLLOHOSP.NS  0.000091  0.000078      0.000102       0.000056  0.000053  ...
LT.NS          0.000116  0.000080      0.000171       0.000056  0.000078  ...
HDFCLIFE.NS    0.000107  0.000085      0.000123       0.000077  0.000061  ...
M&M.NS         0.000125  0.000081      0.000158       0.000062  0.000083  ...
BHARTIARTL.NS  0.000080  0.000061      0.000115       0.000048  0.000064  ...
JIOFIN.NS      0.000122  0.000063      0.000156       0.000030  0.000042  ...
WIPRO.NS       0.000062  0.000147      0.000094       0.000045  0.000045  ...
ADANIPORTS.NS  0.000138  0.000105      0.000204       0.000060  0.000090  ...
INFY.NS        0.000062  0.000171      0.000081       0.000052  0.000041  ...

Ticker         SHRIRAMFIN.NS  APOLLOHOSP.NS     LT.NS  HDFCLIFE.NS    M&M.NS  \
Ticker
GRASIM.NS           0.000179       0.000090  0.000140     0.000124  0.000141
AXISBANK.NS         0.000245       0.000091  0.000167     0.000129  0.000147
EICHERMOT.NS        0.000177       0.000090  0.000127     0.000103  0.000161
SBIN.NS             0.000216       0.000082  0.000172     0.000116  0.000149
ONGC.NS             0.000130       0.000066  0.000116     0.000073  0.000100
TRENT.NS            0.000164       0.000091  0.000116     0.000107  0.000125
TECHM.NS            0.000089       0.000078  0.000080     0.000085  0.000081
TATASTEEL.NS        0.000200       0.000102  0.000171     0.000123  0.000158
HINDUNILVR.NS       0.000062       0.000056  0.000056     0.000077  0.000062
ITC.NS              0.000085       0.000053  0.000078     0.000061  0.000083
TITAN.NS            0.000155       0.000076  0.000106     0.000096  0.000117
BAJAJFINSV.NS       0.000227       0.000111  0.000142     0.000139  0.000152
TATACONSUM.NS       0.000153       0.000097  0.000105     0.000109  0.000111
ICICIBANK.NS        0.000221       0.000088  0.000158     0.000118  0.000140
HINDALCO.NS         0.000208       0.000111  0.000177     0.000129  0.000162
KOTAKBANK.NS        0.000157       0.000076  0.000114     0.000108  0.000107
MARUTI.NS           0.000164       0.000079  0.000122     0.000111  0.000159
POWERGRID.NS        0.000108       0.000047  0.000083     0.000053  0.000080
BEL.NS              0.000195       0.000106  0.000157     0.000102  0.000133
TCS.NS              0.000074       0.000048  0.000062     0.000061  0.000065
BAJFINANCE.NS       0.000265       0.000124  0.000149     0.000145  0.000161
ETERNAL.NS          0.000158       0.000108  0.000108     0.000116  0.000143
ULTRACEMCO.NS       0.000163       0.000094  0.000136     0.000110  0.000133
ASIANPAINT.NS       0.000103       0.000071  0.000086     0.000082  0.000089
TMPV.NS             0.000243       0.000104  0.000181     0.000142  0.000220
MAXHEALTH.NS        0.000092       0.000104  0.000046     0.000062  0.000087
HDFCBANK.NS         0.000150       0.000061  0.000112     0.000108  0.000107
HCLTECH.NS          0.000070       0.000062  0.000065     0.000077  0.000072
COALINDIA.NS        0.000120       0.000058  0.000098     0.000060  0.000087
SBILIFE.NS          0.000124       0.000073  0.000103     0.000166  0.000104
CIPLA.NS            0.000062       0.000075  0.000066     0.000043  0.000077
DRREDDY.NS          0.000060       0.000075  0.000056     0.000056  0.000061
BAJAJ-AUTO.NS       0.000115       0.000071  0.000093     0.000086  0.000128
ADANIENT.NS         0.000247       0.000131  0.000190     0.000174  0.000181
RELIANCE.NS         0.000132       0.000073  0.000106     0.000108  0.000107
INDIGO.NS           0.000170       0.000062  0.000111     0.000108  0.000122
JSWSTEEL.NS         0.000190       0.000097  0.000147     0.000124  0.000158
SUNPHARMA.NS        0.000093       0.000082  0.000072     0.000075  0.000079
NESTLEIND.NS        0.000065       0.000063  0.000050     0.000073  0.000058
NTPC.NS             0.000121       0.000053  0.000103     0.000079  0.000092
SHRIRAMFIN.NS       0.000712       0.000101  0.000188     0.000160  0.000184
APOLLOHOSP.NS       0.000101       0.000379  0.000084     0.000090  0.000090
LT.NS               0.000188       0.000084  0.000283     0.000114  0.000134
HDFCLIFE.NS         0.000160       0.000090  0.000114     0.000331  0.000107
M&M.NS              0.000184       0.000090  0.000134     0.000107  0.000359
BHARTIARTL.NS       0.000115       0.000059  0.000089     0.000089  0.000096
JIOFIN.NS           0.000194       0.000067  0.000142     0.000090  0.000122
WIPRO.NS            0.000078       0.000068  0.000074     0.000071  0.000075
ADANIPORTS.NS       0.000205       0.000103  0.000168     0.000138  0.000145
INFY.NS             0.000075       0.000055  0.000073     0.000077  0.000071

Ticker         BHARTIARTL.NS  JIOFIN.NS  WIPRO.NS  ADANIPORTS.NS   INFY.NS
Ticker
GRASIM.NS           0.000115   0.000101  0.000073       0.000162  0.000064
AXISBANK.NS         0.000093   0.000116  0.000071       0.000170  0.000075
EICHERMOT.NS        0.000088   0.000114  0.000055       0.000137  0.000053
SBIN.NS             0.000103   0.000122  0.000066       0.000200  0.000064
ONGC.NS             0.000081   0.000109  0.000079       0.000144  0.000058
TRENT.NS            0.000080   0.000122  0.000062       0.000138  0.000062
TECHM.NS            0.000061   0.000063  0.000147       0.000105  0.000171
TATASTEEL.NS        0.000115   0.000156  0.000094       0.000204  0.000081
HINDUNILVR.NS       0.000048   0.000030  0.000045       0.000060  0.000052
ITC.NS              0.000064   0.000042  0.000045       0.000090  0.000041
TITAN.NS            0.000072   0.000082  0.000062       0.000123  0.000061
BAJAJFINSV.NS       0.000100   0.000107  0.000076       0.000171  0.000077
TATACONSUM.NS       0.000086   0.000057  0.000067       0.000143  0.000073
ICICIBANK.NS        0.000099   0.000082  0.000068       0.000168  0.000072
HINDALCO.NS         0.000125   0.000116  0.000108       0.000202  0.000102
KOTAKBANK.NS        0.000070   0.000085  0.000054       0.000120  0.000062
MARUTI.NS           0.000084   0.000080  0.000058       0.000134  0.000057
POWERGRID.NS        0.000063   0.000109  0.000045       0.000102  0.000034
BEL.NS              0.000090   0.000164  0.000062       0.000189  0.000052
TCS.NS              0.000047   0.000050  0.000126       0.000067  0.000154
BAJFINANCE.NS       0.000104   0.000117  0.000073       0.000179  0.000084
ETERNAL.NS          0.000067   0.000164  0.000103       0.000200  0.000093
ULTRACEMCO.NS       0.000094   0.000105  0.000073       0.000153  0.000063
ASIANPAINT.NS       0.000063   0.000077  0.000049       0.000104  0.000052
TMPV.NS             0.000119   0.000167  0.000104       0.000212  0.000095
MAXHEALTH.NS        0.000059   0.000090  0.000046       0.000088  0.000042
HDFCBANK.NS         0.000071   0.000097  0.000057       0.000117  0.000061
HCLTECH.NS          0.000058   0.000059  0.000142       0.000076  0.000170
COALINDIA.NS        0.000056   0.000123  0.000063       0.000130  0.000042
SBILIFE.NS          0.000071   0.000089  0.000062       0.000121  0.000059
CIPLA.NS            0.000056   0.000076  0.000048       0.000078  0.000041
DRREDDY.NS          0.000042   0.000051  0.000058       0.000070  0.000051
BAJAJ-AUTO.NS       0.000080   0.000091  0.000058       0.000111  0.000050
ADANIENT.NS         0.000137   0.000233  0.000104       0.000444  0.000091
RELIANCE.NS         0.000086   0.000124  0.000071       0.000141  0.000071
INDIGO.NS           0.000076   0.000163  0.000058       0.000143  0.000056
JSWSTEEL.NS         0.000116   0.000111  0.000089       0.000192  0.000086
SUNPHARMA.NS        0.000063   0.000065  0.000054       0.000100  0.000051
NESTLEIND.NS        0.000043   0.000039  0.000044       0.000061  0.000044
NTPC.NS             0.000070   0.000126  0.000052       0.000135  0.000044
SHRIRAMFIN.NS       0.000115   0.000194  0.000078       0.000205  0.000075
APOLLOHOSP.NS       0.000059   0.000067  0.000068       0.000103  0.000055
LT.NS               0.000089   0.000142  0.000074       0.000168  0.000073
HDFCLIFE.NS         0.000089   0.000090  0.000071       0.000138  0.000077
M&M.NS              0.000096   0.000122  0.000075       0.000145  0.000071
BHARTIARTL.NS       0.000330   0.000049  0.000050       0.000115  0.000059
JIOFIN.NS           0.000049   0.000431  0.000080       0.000213  0.000049
WIPRO.NS            0.000050   0.000080  0.000262       0.000083  0.000145
ADANIPORTS.NS       0.000115   0.000213  0.000083       0.000536  0.000075
INFY.NS             0.000059   0.000049  0.000145       0.000075  0.000285

[50 rows x 50 columns]

In [ ]:
features = pd.DataFrame(index=prices.index)
features["market_return"] = returns.mean(axis=1)
features["market_volatility"] = returns.std(axis=1)
print(features.head())

            market_return  market_volatility
Date
2015-01-01            NaN                NaN
2015-01-02       0.007491           0.011629
2015-01-05      -0.001317           0.012334
2015-01-06      -0.023732           0.014705
2015-01-07       0.004256           0.024851

In [ ]:
#testinf 
stock = "RELIANCE.NS"
stock_features = pd.DataFrame(index=prices.index)
stock_features["return_1d"] = returns[stock]
stock_features["return_5d"] = prices[stock].pct_change(5)
stock_features["return_20d"] = prices[stock].pct_change(20)
stock_features["ma_20"] = prices[stock].rolling(20).mean()
stock_features["ma_50"] = prices[stock].rolling(50).mean()
stock_features["volatility_20d"] = returns[stock].rolling(20).std()
print(stock_features.head(25))

            return_1d  return_5d  return_20d       ma_20  ma_50  \
Date
2015-01-01        NaN        NaN         NaN         NaN    NaN
2015-01-02  -0.002647        NaN         NaN         NaN    NaN
2015-01-05  -0.010954        NaN         NaN         NaN    NaN
2015-01-06  -0.045385        NaN         NaN         NaN    NaN
2015-01-07   0.021768        NaN         NaN         NaN    NaN
2015-01-08  -0.014339  -0.051639         NaN         NaN    NaN
2015-01-09   0.021673  -0.028513         NaN         NaN    NaN
2015-01-12  -0.011624  -0.029172         NaN         NaN    NaN
2015-01-13  -0.008409   0.008432         NaN         NaN    NaN
2015-01-14  -0.009725  -0.022650         NaN         NaN    NaN
2015-01-15   0.035092   0.026364         NaN         NaN    NaN
2015-01-16   0.006306   0.010926         NaN         NaN    NaN
2015-01-19   0.011441   0.034517         NaN         NaN    NaN
2015-01-20   0.026601   0.071043         NaN         NaN    NaN
2015-01-21   0.004097   0.085993         NaN         NaN    NaN
2015-01-22  -0.025365   0.022563         NaN         NaN    NaN
2015-01-23   0.003564   0.019777         NaN         NaN    NaN
2015-01-27   0.002424   0.010686         NaN         NaN    NaN
2015-01-28   0.020021   0.004208         NaN         NaN    NaN
2015-01-29   0.024866   0.024979         NaN  186.269000    NaN
2015-01-30  -0.015225   0.035643    0.030803  186.560281    NaN
2015-02-02  -0.007867   0.023847    0.025408  186.799910    NaN
2015-02-03   0.032542   0.054609    0.070503  187.457558    NaN
2015-02-04  -0.009386   0.024205    0.110872  188.444830    NaN
2015-02-05  -0.005491  -0.006133    0.081236  189.183952    NaN

            volatility_20d
Date
2015-01-01             NaN
2015-01-02             NaN
2015-01-05             NaN
2015-01-06             NaN
2015-01-07             NaN
2015-01-08             NaN
2015-01-09             NaN
2015-01-12             NaN
2015-01-13             NaN
2015-01-14             NaN
2015-01-15             NaN
2015-01-16             NaN
2015-01-19             NaN
2015-01-20             NaN
2015-01-21             NaN
2015-01-22             NaN
2015-01-23             NaN
2015-01-27             NaN
2015-01-28             NaN
2015-01-29             NaN
2015-01-30        0.020023
2015-02-02        0.020116
2015-02-03        0.021035
2015-02-04        0.017932
2015-02-05        0.017659

In [382]:
df.head()

Ticker        SBIN.NS                                               \
Price            Open       High        Low      Close      Volume
Date
2006-01-02  65.606269  65.983728  64.862135  65.059853  21240601.0
2006-01-03  65.289921  65.786008  65.138934  65.573914  17462401.0
2006-01-04  65.836328  66.361181  65.836328  65.994507  19420938.0
2006-01-05  66.260513  67.975263  66.087957  67.676888  42574671.0
2006-01-06  67.655344  68.302424  66.947157  67.594231  23846595.0

Ticker     AXISBANK.NS                                              ...  \
Price             Open       High        Low      Close     Volume  ...
Date                                                                ...
2006-01-02   51.017543  51.279618  50.056594  50.371086   715590.0  ...
2006-01-03   50.703054  51.332035  50.406034  50.598221   419965.0  ...
2006-01-04   51.192260  52.196887  50.842826  51.803772  1448085.0  ...
2006-01-05   51.803783  53.376241  51.375727  53.061752  3013255.0  ...
2006-01-06   53.987740  55.123403  53.131624  54.835121  2035155.0  ...

Ticker         INFY.NS                                                  \
Price             Open        High         Low       Close      Volume
Date
2006-01-02  118.209023  118.209023  116.872440  117.122070   6648000.0
2006-01-03  117.540774  118.523557  117.110318  118.205132   7959936.0
2006-01-04  118.370246  120.489121  117.745191  120.107803  12552928.0
2006-01-05  120.449762  120.681695  119.555431  120.092026   7556560.0
2006-01-06  119.899390  120.685616  118.651257  120.025185  17007808.0

Ticker     ADANIPORTS.NS
Price               Open High Low Close Volume
Date
2006-01-02           NaN  NaN NaN   NaN    NaN
2006-01-03           NaN  NaN NaN   NaN    NaN
2006-01-04           NaN  NaN NaN   NaN    NaN
2006-01-05           NaN  NaN NaN   NaN    NaN
2006-01-06           NaN  NaN NaN   NaN    NaN

[5 rows x 250 columns]

In [ ]:
#creating empty lib
all_features = {}
for stock in ticks:
    stock_features = pd.DataFrame(index=prices.index)
    stock_features["return_1d"] = returns[stock]
    stock_features["return_5d"] = prices[stock].pct_change(5)
    stock_features["return_20d"] = prices[stock].pct_change(20)
    stock_features["ma_20"] = prices[stock].rolling(20).mean()
    stock_features["ma_50"] = prices[stock].rolling(50).mean()
    stock_features["volatility_20d"] = returns[stock].rolling(20).std()
    stock_features = stock_features.replace([np.inf, -np.inf], np.nan)
    stock_features = stock_features.dropna()
    all_features[stock] = stock_features

print("Companies with features:", len(all_features))

Companies with features: 50

In [ ]:
for stock in ticks:    
    print(stock, all_features[stock].shape)

ADANIENT.NS (2833, 6)
ADANIPORTS.NS (2833, 6)
APOLLOHOSP.NS (2833, 6)
ASIANPAINT.NS (2833, 6)
AXISBANK.NS (2833, 6)
BAJAJ-AUTO.NS (2833, 6)
BAJAJFINSV.NS (2833, 6)
BAJFINANCE.NS (2833, 6)
BEL.NS (2833, 6)
BHARTIARTL.NS (2833, 6)
CIPLA.NS (2833, 6)
COALINDIA.NS (2833, 6)
DRREDDY.NS (2833, 6)
EICHERMOT.NS (2833, 6)
ETERNAL.NS (1216, 6)
GRASIM.NS (2833, 6)
HCLTECH.NS (2833, 6)
HDFCBANK.NS (2833, 6)
HDFCLIFE.NS (2123, 6)
HINDALCO.NS (2833, 6)
HINDUNILVR.NS (2833, 6)
ICICIBANK.NS (2833, 6)
INDIGO.NS (2621, 6)
INFY.NS (2833, 6)
ITC.NS (2833, 6)
JIOFIN.NS (701, 6)
JSWSTEEL.NS (2833, 6)
KOTAKBANK.NS (2833, 6)
LT.NS (2833, 6)
M&M.NS (2833, 6)
MARUTI.NS (2833, 6)
MAXHEALTH.NS (1445, 6)
NESTLEIND.NS (2833, 6)
NTPC.NS (2833, 6)
ONGC.NS (2833, 6)
POWERGRID.NS (2833, 6)
RELIANCE.NS (2833, 6)
SBILIFE.NS (2155, 6)
SBIN.NS (2833, 6)
SHRIRAMFIN.NS (2833, 6)
SUNPHARMA.NS (2833, 6)
TATACONSUM.NS (2833, 6)
TATASTEEL.NS (2833, 6)
TCS.NS (2833, 6)
TECHM.NS (2833, 6)
TITAN.NS (2833, 6)
TMPV.NS (2833, 6)
TRENT.NS (2833, 6)
ULTRACEMCO.NS (2833, 6)
WIPRO.NS (2833, 6)

In [ ]:
targets = {}
for stock in ticks:
    targets[stock] = returns[stock].shift(-1)
print(targets["RELIANCE.NS"].head())

Date
2015-01-01   -0.002647
2015-01-02   -0.010954
2015-01-05   -0.045385
2015-01-06    0.021768
2015-01-07   -0.014339
Name: RELIANCE.NS, dtype: float64

In [387]:
targets[stock] = returns[stock].shift(-1)

In [ ]:
ml_data = {}
for stock in ticks:
    data = all_features[stock].copy()
    data["target"] = targets[stock]
    data = data.dropna()
    ml_data[stock] = data
print(ml_data["RELIANCE.NS"].head())

            return_1d  return_5d  return_20d       ma_20       ma_50  \
Date
2015-03-16  -0.009410  -0.031679   -0.073750  185.411665  187.489297
2015-03-17   0.017516  -0.002677   -0.066103  184.765734  187.357021
2015-03-18   0.013771   0.014837   -0.037827  184.402029  187.285027
2015-03-19  -0.014390  -0.008856   -0.050463  183.917448  187.201104
2015-03-20  -0.002395   0.004705   -0.053157  183.406773  187.277785

            volatility_20d    target
Date
2015-03-16        0.016399  0.017516
2015-03-17        0.016843  0.013771
2015-03-18        0.016974 -0.014390
2015-03-19        0.017204 -0.002395
2015-03-20        0.017191 -0.014225

In [ ]:
try:
    import xgboost as xgb

except ModuleNotFoundError:

    import subprocess
    import sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "xgboost"])

    import xgboost as xgb
    
print("XGBoost version:", xgb.__version__)

XGBoost version: 3.2.0
XGBoost version: 3.2.0

In [ ]:
train_data = {}
test_data = {}
for stock in ticks:
    data = ml_data[stock]
    split = int(len(data) * 0.7)
    train_data[stock] = data.iloc[:split]
    test_data[stock] = data.iloc[split:]
print("Training rows:", len(train_data["RELIANCE.NS"]))
print("Testing rows:", len(test_data["RELIANCE.NS"]))

Training rows: 1982
Testing rows: 850

In [ ]:
from xgboost import XGBRegressor

stock = "RELIANCE.NS"
X_train = train_data[stock].drop(columns="target")
y_train = train_data[stock]["target"]
model = XGBRegressor(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    random_state=42
)
model.fit(X_train, y_train)
print("Model trained successfully!")

Model trained successfully!

In [ ]:
X_test = test_data["RELIANCE.NS"].drop(columns="target")
y_test = test_data["RELIANCE.NS"]["target"]
predictions = model.predict(X_test)
print(predictions[:10])

[ 1.2872112e-04 -4.3122851e-05 -4.3122851e-05  1.4544509e-03
  3.6729433e-04  2.3996862e-04  2.6147314e-03  1.1345046e-03
  1.2351887e-03  1.2351887e-03]

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 0.01148418607896081
RMSE: 0.015070196463130221
R²  : -0.3612346819085912

In [ ]:
stock = "RELIANCE.NS"
stock_features = pd.DataFrame(index=prices.index)
stock_features["return_1d"] = returns[stock]
stock_features["return_5d"] = prices[stock].pct_change(5)
stock_features["return_20d"] = prices[stock].pct_change(20)
stock_features["ma_20"] = prices[stock].rolling(20).mean()
stock_features["ma_50"] = prices[stock].rolling(50).mean()
stock_features["volatility_20d"] = returns[stock].rolling(20).std()
stock_features["market_return"] = returns.mean(axis=1)
stock_features["market_volatility"] = returns.std(axis=1)
stock_features = stock_features.replace([np.inf, -np.inf], np.nan)
stock_features = stock_features.dropna()
print(stock_features.head())
print("Features:", stock_features.shape[1])

            return_1d  return_5d  return_20d       ma_20       ma_50  \
Date
2015-03-16  -0.009410  -0.031679   -0.073750  185.411665  187.489297
2015-03-17   0.017516  -0.002677   -0.066103  184.765734  187.357021
2015-03-18   0.013771   0.014837   -0.037827  184.402029  187.285027
2015-03-19  -0.014390  -0.008856   -0.050463  183.917448  187.201104
2015-03-20  -0.002395   0.004705   -0.053157  183.406773  187.277785

            volatility_20d  market_return  market_volatility
Date
2015-03-16        0.016399      -0.004361           0.016319
2015-03-17        0.016843       0.012100           0.012773
2015-03-18        0.016974      -0.005882           0.010264
2015-03-19        0.017204      -0.005016           0.012557
2015-03-20        0.017191      -0.010610           0.015992
Features: 8

In [ ]:
stock = "RELIANCE.NS"
reliance_ml = stock_features.copy()
reliance_ml["target"] = returns[stock].shift(-1)
reliance_ml = reliance_ml.dropna()
print(reliance_ml.head())
print("Shape:", reliance_ml.shape)

            return_1d  return_5d  return_20d       ma_20       ma_50  \
Date
2015-03-16  -0.009410  -0.031679   -0.073750  185.411665  187.489297
2015-03-17   0.017516  -0.002677   -0.066103  184.765734  187.357021
2015-03-18   0.013771   0.014837   -0.037827  184.402029  187.285027
2015-03-19  -0.014390  -0.008856   -0.050463  183.917448  187.201104
2015-03-20  -0.002395   0.004705   -0.053157  183.406773  187.277785

            volatility_20d  market_return  market_volatility    target
Date
2015-03-16        0.016399      -0.004361           0.016319  0.017516
2015-03-17        0.016843       0.012100           0.012773  0.013771
2015-03-18        0.016974      -0.005882           0.010264 -0.014390
2015-03-19        0.017204      -0.005016           0.012557 -0.002395
2015-03-20        0.017191      -0.010610           0.015992 -0.014225
Shape: (2832, 9)

In [ ]:
split = int(len(reliance_ml) * 0.8)
reliance_train = reliance_ml.iloc[:split]
reliance_test = reliance_ml.iloc[split:]
X_train = reliance_train.drop(columns="target")
y_train = reliance_train["target"]
X_test = reliance_test.drop(columns="target")
y_test = reliance_test["target"]
print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

Training rows: 2265
Testing rows: 567

In [ ]:
model = XGBRegressor(
    n_estimators=200,
    max_depth=3,
    learning_rate=0.05,
    random_state=42
)
model.fit(X_train, y_train)
print("Improved XGBoost model trained successfully!")

Improved XGBoost model trained successfully!

In [ ]:
predictions = model.predict(X_test)
print(predictions[:10])

[-1.3278554e-03  1.2999711e-03 -1.5034310e-03  4.3046275e-05
 -3.6031599e-04 -7.7045515e-05 -2.1073590e-03  6.4138701e-04
  3.3151081e-03  2.0190720e-02]

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 0.010110976564183345
RMSE: 0.013693494501322382
R²  : -0.02546690913468508

In [ ]:
all_ml_data = {}
for stock in ticks:
    stock_features = pd.DataFrame(index=prices.index)
    stock_features["return_1d"] = returns[stock]
    stock_features["return_5d"] = prices[stock].pct_change(5)
    stock_features["return_20d"] = prices[stock].pct_change(20)
    # Moving averages
    stock_features["ma_20"] = prices[stock].rolling(20).mean()
    stock_features["ma_50"] = prices[stock].rolling(50).mean()
    # Stock risk
    stock_features["volatility_20d"] = returns[stock].rolling(20).std()
    # Market features
    stock_features["market_return"] = returns.mean(axis=1)
    stock_features["market_volatility"] = returns.std(axis=1)
    # Target = next day's return
    stock_features["target"] = returns[stock].shift(-1)




    stock_features = stock_features.replace(
        [np.inf, -np.inf], np.nan
    ).dropna()
    all_ml_data[stock] = stock_features
print("Stocks prepared:", len(all_ml_data))

Stocks prepared: 50

In [430]:
models = {}
predicted_returns = {}
evaluation = {}




for stock in ticks:

    data = all_ml_data[stock]
    split = int(len(data) * 0.8)
    train = data.iloc[:split]
    test = data.iloc[split:]
    X_train = train.drop(columns="target")
    y_train = train["target"]
    X_test = test.drop(columns="target")
    y_test = test["target"]
    model = XGBRegressor(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.0025,
        random_state=45
    )
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    models[stock] = model
    predicted_returns[stock] = predictions[-1]




    evaluation[stock] = {
        "MAE": mean_absolute_error(y_test, predictions),
        "RMSE": np.sqrt(mean_squared_error(y_test, predictions)),
        "R2": r2_score(y_test, predictions)
    }
print("Models trained:", len(models))

Models trained: 50

In [431]:
evaluation_df = pd.DataFrame(evaluation).T
print(evaluation_df)

                    MAE      RMSE        R2
ADANIENT.NS    0.015574  0.025098 -0.018894
ADANIPORTS.NS  0.013791  0.021366 -0.014146
APOLLOHOSP.NS  0.009138  0.012776  0.001598
ASIANPAINT.NS  0.009921  0.013877 -0.018836
AXISBANK.NS    0.010522  0.015047  0.005103
BAJAJ-AUTO.NS  0.011564  0.016058 -0.008860
BAJAJFINSV.NS  0.011479  0.015708 -0.034255
BAJFINANCE.NS  0.012704  0.017658  0.004389
BEL.NS         0.014523  0.020354 -0.019935
BHARTIARTL.NS  0.009777  0.013399  0.002786
CIPLA.NS       0.009611  0.013722 -0.000769
COALINDIA.NS   0.010736  0.015610  0.011813
DRREDDY.NS     0.009943  0.013743  0.000258
EICHERMOT.NS   0.011333  0.016014  0.003332
ETERNAL.NS     0.016160  0.021110 -0.003421
GRASIM.NS      0.010638  0.014438  0.001119
HCLTECH.NS     0.011606  0.016767 -0.013480
HDFCBANK.NS    0.009141  0.012735 -0.001825
HDFCLIFE.NS    0.010273  0.013928 -0.000985
HINDALCO.NS    0.013392  0.018270 -0.005204
HINDUNILVR.NS  0.009366  0.013053  0.000827
ICICIBANK.NS   0.008824  0.012188 -0.004339
INDIGO.NS      0.014085  0.019574 -0.007463
INFY.NS        0.012456  0.017177 -0.019153
ITC.NS         0.008257  0.011698 -0.013135
JIOFIN.NS      0.014254  0.019085 -0.003302
JSWSTEEL.NS    0.011330  0.015608  0.005755
KOTAKBANK.NS   0.009927  0.013991  0.003372
LT.NS          0.011034  0.016712 -0.037315
M&M.NS         0.014027  0.018409 -0.000763
MARUTI.NS      0.010218  0.014354 -0.006469
MAXHEALTH.NS   0.012108  0.016378 -0.033218
NESTLEIND.NS   0.009021  0.012329 -0.004217
NTPC.NS        0.011056  0.015933 -0.025608
ONGC.NS        0.012349  0.018340  0.000147
POWERGRID.NS   0.010908  0.015605 -0.010243
RELIANCE.NS    0.009885  0.013554 -0.004618
SBILIFE.NS     0.009623  0.013012 -0.008440
SBIN.NS        0.010313  0.015526  0.005703
SHRIRAMFIN.NS  0.016796  0.022965 -0.002888
SUNPHARMA.NS   0.008983  0.012387 -0.002625
TATACONSUM.NS  0.010796  0.014656 -0.000163
TATASTEEL.NS   0.012579  0.017650  0.006825
TCS.NS         0.010594  0.015309 -0.000903
TECHM.NS       0.012671  0.016950 -0.019647
TITAN.NS       0.010479  0.014463 -0.003786
TMPV.NS        0.014837  0.025594 -0.003810
TRENT.NS       0.016665  0.027433 -0.014968
ULTRACEMCO.NS  0.010786  0.014738 -0.002047
WIPRO.NS       0.012248  0.017023  0.002559

In [432]:
predicted_df = pd.Series(predicted_returns, name="Predicted_Return")
print(predicted_df.sort_values(ascending=False))

BEL.NS           0.003650
JIOFIN.NS        0.002287
POWERGRID.NS     0.002059
MAXHEALTH.NS     0.002005
TRENT.NS         0.001894
ETERNAL.NS       0.001633
ADANIENT.NS      0.001560
NTPC.NS          0.001344
BAJAJ-AUTO.NS    0.001128
TATACONSUM.NS    0.001059
TITAN.NS         0.000984
BAJFINANCE.NS    0.000972
ASIANPAINT.NS    0.000888
RELIANCE.NS      0.000855
BHARTIARTL.NS    0.000818
SUNPHARMA.NS     0.000818
M&M.NS           0.000787
HINDALCO.NS      0.000733
ICICIBANK.NS     0.000710
NESTLEIND.NS     0.000707
JSWSTEEL.NS      0.000676
INFY.NS          0.000670
HCLTECH.NS       0.000649
GRASIM.NS        0.000635
HINDUNILVR.NS    0.000629
ULTRACEMCO.NS    0.000624
MARUTI.NS        0.000566
ITC.NS           0.000506
ADANIPORTS.NS    0.000483
INDIGO.NS        0.000452
APOLLOHOSP.NS    0.000413
TCS.NS           0.000412
AXISBANK.NS      0.000400
SBILIFE.NS       0.000359
ONGC.NS          0.000316
WIPRO.NS         0.000276
EICHERMOT.NS     0.000238
SHRIRAMFIN.NS    0.000152
SBIN.NS          0.000141
HDFCLIFE.NS      0.000126
TATASTEEL.NS     0.000038
COALINDIA.NS    -0.000008
CIPLA.NS        -0.000011
LT.NS           -0.000048
DRREDDY.NS      -0.000330
BAJAJFINSV.NS   -0.000410
TMPV.NS         -0.000624
HDFCBANK.NS     -0.001057
KOTAKBANK.NS    -0.001314
TECHM.NS        -0.006643
Name: Predicted_Return, dtype: float32

In [ ]:
from sklearn.model_selection import TimeSeriesSplit, RandomizedSearchCV
from xgboost import XGBRegressor

tscv = TimeSeriesSplit(n_splits=3)
param_grid = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [2, 3, 4, 5],
    "learning_rate": [0.01, 0.03, 0.05, 0.1],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0]
}
print("Hyperparameter tuning setup complete.")

Hyperparameter tuning setup complete.

In [ ]:
stock = "RELIANCE.NS"
data = all_ml_data[stock]
split = int(len(data) * 0.8)

train = data.iloc[:split]
test = data.iloc[split:]

X_train = train.drop(columns="target")
y_train = train["target"]

X_test = test.drop(columns="target")
y_test = test["target"]

base_model = XGBRegressor(
    objective="reg:squarederror",
    random_state=42
)
search = RandomizedSearchCV(
    estimator=base_model,
    param_distributions=param_grid,
    n_iter=20,
    scoring="r2",
    cv=tscv,
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

print("Best parameters:")
print(search.best_params_)

print("\nBest CV R²:")
print(search.best_score_)

Best parameters:
{'subsample': 0.8, 'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.01, 'colsample_bytree': 1.0}

Best CV R²:
-0.01709457972476088

In [ ]:
tuned_models = {}
tuned_predictions = {}
tuned_evaluation = {}
best_params = {}

for stock in ticks:

    print(f"Tuning {stock}...")
    data = all_ml_data[stock]
    split = int(len(data) * 0.8)
    train = data.iloc[:split]
    test = data.iloc[split:]
    X_train = train.drop(columns="target")
    y_train = train["target"]
    X_test = test.drop(columns="target")
    y_test = test["target"]
    base_model = XGBRegressor(
        objective="reg:squarederror",
        random_state=42
    )
    search = RandomizedSearchCV(
        estimator=base_model,
        param_distributions=param_grid,
        n_iter=20,
        scoring="r2",
        cv=tscv,
        random_state=42,
        n_jobs=-1
    )
    search.fit(X_train, y_train)
    best_model = search.best_estimator_
    predictions = best_model.predict(X_test)
    tuned_models[stock] = best_model
    tuned_predictions[stock] = predictions[-1]
    best_params[stock] = search.best_params_
    tuned_evaluation[stock] = {
        "MAE": mean_absolute_error(y_test, predictions),
        "RMSE": np.sqrt(mean_squared_error(y_test, predictions)),
        "R2": r2_score(y_test, predictions)
    }
print("\nTuning completed for:", len(tuned_models), "stocks")

Tuning ADANIENT.NS...
Tuning ADANIPORTS.NS...
Tuning APOLLOHOSP.NS...
Tuning ASIANPAINT.NS...
Tuning AXISBANK.NS...
Tuning BAJAJ-AUTO.NS...
Tuning BAJAJFINSV.NS...
Tuning BAJFINANCE.NS...
Tuning BEL.NS...
Tuning BHARTIARTL.NS...
Tuning CIPLA.NS...
Tuning COALINDIA.NS...
Tuning DRREDDY.NS...
Tuning EICHERMOT.NS...
Tuning ETERNAL.NS...
Tuning GRASIM.NS...
Tuning HCLTECH.NS...
Tuning HDFCBANK.NS...
Tuning HDFCLIFE.NS...
Tuning HINDALCO.NS...
Tuning HINDUNILVR.NS...
Tuning ICICIBANK.NS...
Tuning INDIGO.NS...
Tuning INFY.NS...
Tuning ITC.NS...
Tuning JIOFIN.NS...
Tuning JSWSTEEL.NS...
Tuning KOTAKBANK.NS...
Tuning LT.NS...
Tuning M&M.NS...
Tuning MARUTI.NS...
Tuning MAXHEALTH.NS...
Tuning NESTLEIND.NS...
Tuning NTPC.NS...
Tuning ONGC.NS...
Tuning POWERGRID.NS...
Tuning RELIANCE.NS...
Tuning SBILIFE.NS...
Tuning SBIN.NS...
Tuning SHRIRAMFIN.NS...
Tuning SUNPHARMA.NS...
Tuning TATACONSUM.NS...
Tuning TATASTEEL.NS...
Tuning TCS.NS...
Tuning TECHM.NS...
Tuning TITAN.NS...
Tuning TMPV.NS...
Tuning TRENT.NS...
Tuning ULTRACEMCO.NS...
Tuning WIPRO.NS...

Tuning completed for: 50 stocks

In [ ]:
tuned_evaluation_df = pd.DataFrame(tuned_evaluation).T
print(tuned_evaluation_df)

                    MAE      RMSE        R2
ADANIENT.NS    0.015769  0.025315 -0.036578
ADANIPORTS.NS  0.013792  0.021428 -0.020094
APOLLOHOSP.NS  0.009133  0.012774  0.001914
ASIANPAINT.NS  0.010024  0.014003 -0.037340
AXISBANK.NS    0.010533  0.015054  0.004171
BAJAJ-AUTO.NS  0.011747  0.016266 -0.035125
BAJAJFINSV.NS  0.011509  0.015796 -0.045884
BAJFINANCE.NS  0.012703  0.017687  0.001081
BEL.NS         0.016208  0.021882 -0.178837
BHARTIARTL.NS  0.009806  0.013448 -0.004492
CIPLA.NS       0.009678  0.013760 -0.006417
COALINDIA.NS   0.010954  0.015791 -0.011178
DRREDDY.NS     0.009972  0.013753 -0.001325
EICHERMOT.NS   0.011361  0.016019  0.002654
ETERNAL.NS     0.016161  0.021376 -0.028836
GRASIM.NS      0.010638  0.014436  0.001523
HCLTECH.NS     0.011519  0.016666 -0.001255
HDFCBANK.NS    0.009738  0.013373 -0.104710
HDFCLIFE.NS    0.010260  0.013920  0.000157
HINDALCO.NS    0.013433  0.018343 -0.013208
HINDUNILVR.NS  0.009369  0.013135 -0.011874
ICICIBANK.NS   0.008828  0.012134  0.004535
INDIGO.NS      0.014081  0.019522 -0.002149
INFY.NS        0.012798  0.017423 -0.048631
ITC.NS         0.008177  0.011605  0.002783
JIOFIN.NS      0.014593  0.019497 -0.047125
JSWSTEEL.NS    0.011301  0.015540  0.014448
KOTAKBANK.NS   0.009962  0.014040 -0.003656
LT.NS          0.011051  0.016735 -0.040198
M&M.NS         0.014299  0.018657 -0.027865
MARUTI.NS      0.010235  0.014350 -0.005811
MAXHEALTH.NS   0.012164  0.016431 -0.039952
NESTLEIND.NS   0.009016  0.012345 -0.006935
NTPC.NS        0.011068  0.015849 -0.014774
ONGC.NS        0.012359  0.018272  0.007572
POWERGRID.NS   0.011424  0.015992 -0.061042
RELIANCE.NS    0.009846  0.013505  0.002566
SBILIFE.NS     0.009692  0.013079 -0.018890
SBIN.NS        0.010380  0.015596 -0.003322
SHRIRAMFIN.NS  0.016865  0.023029 -0.008475
SUNPHARMA.NS   0.009038  0.012437 -0.010597
TATACONSUM.NS  0.010749  0.014601  0.007311
TATASTEEL.NS   0.012616  0.017713 -0.000310
TCS.NS         0.010524  0.015233  0.009009
TECHM.NS       0.012926  0.017227 -0.053334
TITAN.NS       0.010472  0.014477 -0.005724
TMPV.NS        0.015052  0.025741 -0.015325
TRENT.NS       0.017002  0.027613 -0.028346
ULTRACEMCO.NS  0.010796  0.014707  0.002163
WIPRO.NS       0.012272  0.017027  0.002083

In [ ]:
print("\nR² statistics:")
print(tuned_evaluation_df["R2"].describe())
print("\nStocks with positive R²:")
print(tuned_evaluation_df[tuned_evaluation_df["R2"] > 0]["R2"])

R² statistics:
count    50.000000
mean     -0.018313
std       0.032436
min      -0.178837
25%      -0.028714
50%      -0.006676
75%       0.001412
max       0.014448
Name: R2, dtype: float64

Stocks with positive R²:
APOLLOHOSP.NS    0.001914
AXISBANK.NS      0.004171
BAJFINANCE.NS    0.001081
EICHERMOT.NS     0.002654
GRASIM.NS        0.001523
HDFCLIFE.NS      0.000157
ICICIBANK.NS     0.004535
ITC.NS           0.002783
JSWSTEEL.NS      0.014448
ONGC.NS          0.007572
RELIANCE.NS      0.002566
TATACONSUM.NS    0.007311
TCS.NS           0.009009
ULTRACEMCO.NS    0.002163
WIPRO.NS         0.002083
Name: R2, dtype: float64